name: mynul_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get: ^4.6.6
  http: ^1.4.0
  path: ^1.9.1
  permission_handler: ^12.0.1
  provider: ^6.1.5
  rive: ^0.13.20
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename_app: ^1.6.5
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/images/


flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      remove_alpha_ios: true
      image_path: "assets/images/login-book.png"
      min_sdk_android: 21 
      adaptive_icon_background: "#FFFFFF"
      adaptive_icon_foreground: "assets/images/login-book.png"
